"""The written contract for a memory document, generated from the model.

`.siatt/schema.md` has two audiences: a person opening the repo, and the
consolidation model deciding what to write. Both act on it, so it must describe
`Frontmatter` as it actually is. Generating it from the model's own fields and
descriptions is the only version of that which stays true — a hand-maintained
copy drifts, and a drifted contract is worse than none, because the model
believes it.
"""

from __future__ import annotations

from typing import Any, get_args, get_origin

SCHEMA_VERSION = 2

_HEADER = """<!-- Generated by Siatt from siatt/memory/document.py. Do not edit by hand. -->

# Memory document schema (v{version})

Every file under `memory/` is Markdown with a YAML frontmatter block. The
frontmatter is the contract; the body is ordinary prose written for a human.

## Frontmatter fields

| field | type | required | default | meaning |
| --- | --- | --- | --- | --- |
"""

_RULES = """
## Rules

- **`id` is forever.** Files move between directories as the corpus is
  reorganized; links resolve through `.siatt/manifest.json` by id, so a moved
  file keeps every inbound link. Rewriting an id orphans them.
- **`visibility` is always `workspace`.** Siatt serves one person, so there is
  one pool of memory and nothing filters on this. A fact learned in one channel
  answers a question asked in another.
- **One claim per memory.** Split rather than append when a file starts covering
  two subjects; the reorganizer will do it anyway, and it does it worse.
- **Link generously** with `[[mem_01K8...]]` or `[[people/jane]]`. Both forms
  resolve through the manifest, and a link to a memory that was later merged
  away follows the `supersedes` chain to whatever replaced it.
- **Deletion is a transition, not an erasure.** A memory moves to
  `memory/archive/` first and is removed only after the retention floor. Git
  history keeps the blob either way.
- **The body is yours.** Siatt rewrites frontmatter canonically and passes the
  body through untouched, so hand edits to the prose survive.

## Example

```markdown
---
id: mem_01K8XQ4W2N7B6VJ3ZC9F0RTKME
type: person
title: Deploy pipeline ownership
tags: [infra, ownership]
visibility: workspace
created: 2026-09-03T10:12:00Z
updated: 2026-09-03T10:12:00Z
confidence: 0.9
salience: 0.7
pinned: false
source_refs: [slack://T01/C0123/1756890000.123]
supersedes: []
---

Jane owns the deploy pipeline. See [[projects/deploy]] for the runbook.
```

## Layout

```
memory/
  README.md          generated index; the human entry point
  people/            one file per person
  projects/
  topics/
  facts/             atomic durable facts that fit nowhere else
  journal/2026/09/   nightly digests
  archive/           soft-deleted, awaiting collection
  .siatt/             generated machinery; never written by a patch plan
```
"""

_README_MD = """# Siatt long-term memory

This repository is the long-term memory of a [Siatt](https://github.com/KeunwooPark/siatt)
agent. It is the source of truth: the agent's SQLite database is a derived index
that can be deleted and rebuilt from these files at any time.

**This repository is private, and must stay private.** It accumulates whatever
the agent was told, including things said in DMs and private channels. Siatt
refuses to run against a public memory repo.

## Working with it by hand

Every memory is a Markdown file under `memory/`, and every change the agent
makes is an ordinary commit. So:

- To correct a belief, edit the file. The agent will read your version.
- To see what it decided to believe and when, read the log.
- To undo something, `git revert` it.

`memory/.siatt/schema.md` describes the frontmatter contract both you and the
agent are writing against. Everything under `.siatt/` is generated — the agent
rewrites it, so hand edits there will not survive.
"""

_INDEX_MD = """# Memory index

<!-- Siatt regenerates the listing below. Text above this comment is preserved. -->

Nothing here yet. Memories will appear as the agent promotes them out of
conversation.
"""


def render_schema_md() -> str:
    """The contract written to `.siatt/schema.md`, derived from `Frontmatter`."""
    # Imported here rather than at module scope: document.py needs
    # SCHEMA_VERSION from this module, and the manifest needs both.
    from siatt.memory.document import Frontmatter

    rows = []
    for name, field in Frontmatter.model_fields.items():
        required = field.is_required()
        default = "—" if required else _default(field.get_default(call_default_factory=True))
        rows.append(
            f"| `{name}` | {_type_name(field.annotation)} | {'yes' if required else 'no'} "
            f"| {default} | {_cell(field.description)} |"
        )
    return _HEADER.format(version=SCHEMA_VERSION) + "\n".join(rows) + "\n" + _RULES


def render_repo_readme() -> str:
    """The repository's front page, written for the human who owns it."""
    return _README_MD


def render_memory_index() -> str:
    """The initial `memory/README.md`."""
    return _INDEX_MD


_SCALARS = {"str": "string", "int": "integer", "bool": "boolean", "float": "number"}


def _type_name(annotation: Any) -> str:
    if annotation is None:
        return "—"
    # A Literal renders as its own choices, which is the useful thing to show a
    # model that has to pick one.
    choices = get_args(annotation)
    if choices and all(isinstance(choice, str) for choice in choices):
        return _cell(" | ".join(f"`{choice}`" for choice in choices))
    if get_origin(annotation) is list:
        return f"list of {_type_name(choices[0]) if choices else 'anything'}"
    name = getattr(annotation, "__name__", str(annotation))
    return _SCALARS.get(name, name)


def _default(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, list):
        return f"`{value}`" if value else "`[]`"
    return f"`{str(value).lower()}`" if isinstance(value, bool) else f"`{value}`"


def _cell(text: str | None) -> str:
    """Escape a value for a Markdown table cell.

    An unescaped pipe in a field description — `workspace | channel:C0123` is
    the obvious one — silently splits the row into extra columns.
    """
    return (text or "").replace("|", "\\|")
